-- ============================================================================
-- БАЗОВАЯ МИГРАЦИЯ (baseline) — реконструкция текущей схемы Supabase
-- ============================================================================
--
-- ВАЖНО, ПРОЧИТАЙТЕ ПЕРЕД ИСПОЛЬЗОВАНИЕМ:
--
-- Этот файл НЕ является дампом реальной базы данных. Supabase CLI (`supabase
-- db pull`/`db dump`) требует Docker Desktop для получения точной схемы
-- с сервера — на момент написания миграции Docker недоступен в рабочем
-- окружении. Вместо этого схема РЕКОНСТРУИРОВАНА вручную по факту того, какие
-- поля/таблицы использует код: backend/clarify-backend/models.py (SQLAlchemy)
-- и прямые вызовы Supabase из frontend/lib/**/*.dart (INSERT/SELECT/RPC).
--
-- Что НЕ покрыто этой реконструкцией и требует ручной сверки с реальной
-- базой (Supabase Studio → Database) перед тем, как считать эту миграцию
-- полной картиной:
--   1. RLS-политики (Row Level Security) — в коде не отражены вообще, вся
--      защита данных живёт только в БД. Ниже RLS включен для каждой таблицы
--      (это она и так наверняка включена, раз приложение работает через
--      публичный anon-ключ), но САМИ ПОЛИТИКИ (кто что может читать/писать)
--      не реконструированы — их тела нужно скопировать из Supabase Studio.
--   2. Тела RPC-функций get_workspace_members и invite_user_by_email — из
--      кода известна только сигнатура вызова (имена и типы параметров),
--      сама SQL-логика внутри функций не видна нигде в кодовой базе.
--      Ниже — только заглушки с комментарием, не рабочий код.
--   3. Индексы сверх очевидных (PK/FK), триггеры, точные NOT NULL/CHECK
--      ограничения, политики Storage-бакета `avatars`.
--
-- Как использовать правильно:
--   - Если это ПЕРВАЯ миграция для уже существующей продовой базы — не
--     применяйте её через `supabase db push` (упадёт на "relation already
--     exists"). Вместо этого "забазлайньте" её как уже применённую:
--     `supabase migration repair --status applied 20260722195748`
--     после чего дальнейшие изменения делайте только новыми миграциями.
--   - Если сомневаетесь в точности реконструкции — сначала сверьте эту
--     миграцию с реальной схемой в Supabase Studio (или установите Docker
--     и перевыпустите её через `supabase db pull`).
--
-- ============================================================================

-- --- workspaces ---
create table if not exists public.workspaces (
    id bigint generated by default as identity primary key,
    name text not null,
    owner_id uuid not null,
    created_at timestamptz not null default now()
);

-- --- workspace_members ---
create table if not exists public.workspace_members (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references public.workspaces (id) on delete cascade,
    user_id uuid not null,
    role text not null default 'editor',
    created_at timestamptz not null default now()
);

-- --- tasks ---
-- ПРИМЕЧАНИЕ: due_date/due_time хранятся как text ('ДД.ММ.ГГГГ' / 'ЧЧ:ММ'),
-- а не date/time — это сознательно сохранено как есть в этой базовой
-- миграции, перевод на типизированные колонки — отдельная миграция (P3.3 /
-- REQ-R3-03 в docs/PRD.md), которая переносит данные, а не просто меняет тип.
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    user_id uuid,
    assigned_to uuid,
    workspace_id bigint references public.workspaces (id) on delete cascade,
    title text not null,
    due_date text,
    due_time text,
    note text,
    is_completed boolean not null default false,
    priority text not null default 'none',
    tags text,
    parent_id bigint references public.tasks (id) on delete cascade,
    recurrence text,
    folder text
);

create index if not exists tasks_title_idx on public.tasks (title);
create index if not exists tasks_user_id_idx on public.tasks (user_id);
create index if not exists tasks_workspace_id_idx on public.tasks (workspace_id);
create index if not exists tasks_parent_id_idx on public.tasks (parent_id);

-- --- user_status (статус Zen-режима) ---
create table if not exists public.user_status (
    user_id uuid primary key,
    is_in_zen boolean not null default false,
    zen_until timestamptz
);

-- --- task_comments (обсуждение задачи) ---
create table if not exists public.task_comments (
    id bigint generated by default as identity primary key,
    task_id bigint not null references public.tasks (id) on delete cascade,
    user_id uuid not null,
    text text not null,
    created_at timestamptz not null default now()
);

create index if not exists task_comments_task_id_idx on public.task_comments (task_id);

-- ============================================================================
-- RLS — включаем на всех таблицах (приложение работает через публичный
-- anon-ключ, значит RLS в реальной базе почти наверняка уже включён).
-- САМИ ПОЛИТИКИ ниже НЕ реконструированы (см. пункт 1 выше) — без них после
-- `enable row level security` доступ к таблицам будет ПОЛНОСТЬЮ закрыт.
-- Это осознанно: лучше явная ошибка "нет доступа", чем тихая иллюзия
-- защищённости от несуществующих политик. Перед применением на реальном
-- проекте political-блок нужно скопировать из Supabase Studio.
-- ============================================================================
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.tasks enable row level security;
alter table public.user_status enable row level security;
alter table public.task_comments enable row level security;

-- ============================================================================
-- RPC-функции — ЗАГЛУШКИ, НЕ РАБОЧИЙ КОД.
-- Реальные тела функций неизвестны (нигде не встречаются в кодовой базе),
-- известны только сигнатуры вызова из Dart (`.rpc('get_workspace_members',
-- params: {'ws_id': wsId})` и `.rpc('invite_user_by_email', params: {...})`).
-- Перед реальным использованием — скопировать тела функций из Supabase
-- Studio → Database → Functions.
-- ============================================================================
-- create or replace function public.get_workspace_members(ws_id bigint)
-- returns table (user_id uuid, full_name text, avatar_url text, role text)
-- language sql as $$ /* тело неизвестно — см. Supabase Studio */ $$;
--
-- create or replace function public.invite_user_by_email(invitee_email text, ws_id bigint)
-- returns text
-- language plpgsql as $$ /* тело неизвестно — см. Supabase Studio */ $$;
